install.packages("lubridate")
install.packages("dplyr")
install.packages("Rcpp")
install.packages("udunits2")
install.packages("units")
install.packages("ggplot2")
install.packages("remotes")
remotes::install_github("sensebox/opensensmapr@development")
