install.packages("lubridate")
install.packages("dplyr")
install.packages("rgdal")
install.packages("rgeos")
install.package("udunits2")
install.packages("units")
install.packages("sf")
install.packages("sp")
install.packages("ggplot2")
install.packages("devtools")
devtools::install_github('sensebox/opensensmapr@development', force=TRUE)
