install.packages("lubridate")
install.packages("tidyverse")
install.packages("units")
install.packages("sf")
install.packages("lindia")
install.packages('devtools')
devtools::install_github('sensebox/opensensmapr@master')
